attempting to run cypress tests as a separate job in docker with Cypress pre-installed

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -97,37 +97,37 @@ jobs:
         echo $IP
       working-directory: ../plugin-infrastructure/deploy/plugins
 
+  # Run Cypress tests
+  cypress-run:
+    runs-on: ubuntu-latest
+    # Docker image with Cypress pre-installed
+    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
+    container: cypress/included:7.0.0
+    steps:
+      - uses: actions/checkout@v1
+        with:
+          repository: AltaPay/plugin-magento2
+          ref: '${{env.TEST_BRANCH_NAME}}'
+          path: plugin-magento2
 
-    # Run Cypress tests   
-    - uses: actions/checkout@v1
-      with:
-        repository: AltaPay/plugin-magento2
-        ref: '${{env.TEST_BRANCH_NAME}}'
-        path: plugin-magento2
+      - name: Create Cypress fixture config json
+        id: create-json-2  # Second ID
+        uses: jsdaniell/create-json@1.1.2
+        with:
+          name: "config.json"
+          json: '{"shopURL": "http://${{env.IP}}/magento","adminURL": "http://${{env.IP}}/magento/admin","adminUsername": "${{secrets.CMS_ADMIN_USER}}","adminPass": "${{secrets.CMS_ADMIN_PASS}}", "CC_TERMINAL_NAME": "${{secrets.CC_TERMINAL_NAME}}", "KLARNA_DKK_TERMINAL_NAME": "${{secrets.KLARNA_DKK_TERMINAL_NAME}}", "SUBSCRIPTION_TERMINAL_NAME": "${{secrets.SUBSCRIPTION_TERMINAL_NAME}}", "iDEAL_EUR_TERMINAL": "${{secrets.IDEAL_EUR_TERMINAL_NAME}}"}'
+          dir: Tests/integration-tests/cypress/fixtures/
 
-    - name: Create Cypress fixture config json
-      id: create-json-2  # Second ID
-      uses: jsdaniell/create-json@1.1.2
-      with:
-        name: "config.json"
-        json: '{"shopURL": "http://${{env.IP}}/magento","adminURL": "http://${{env.IP}}/magento/admin","adminUsername": "${{secrets.CMS_ADMIN_USER}}","adminPass": "${{secrets.CMS_ADMIN_PASS}}", "CC_TERMINAL_NAME": "${{secrets.CC_TERMINAL_NAME}}", "KLARNA_DKK_TERMINAL_NAME": "${{secrets.KLARNA_DKK_TERMINAL_NAME}}", "SUBSCRIPTION_TERMINAL_NAME": "${{secrets.SUBSCRIPTION_TERMINAL_NAME}}", "iDEAL_EUR_TERMINAL": "${{secrets.IDEAL_EUR_TERMINAL_NAME}}"}'
-        dir: Tests/integration-tests/cypress/fixtures/
+      - name: Run Cypress tests
+        run: cypress run --config video=false
+        working-directory: "tests/integration-test"
 
-    - name: Install Cypress Dependencies 
-      run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb && npm i
-      working-directory: Tests/integration-tests
-
-    - name: Run Cypress tests 
-      run: ./node_modules/.bin/cypress run
-      working-directory: Tests/integration-tests
-
-      # after the test run completes
-      # store screenshots
-      # NOTE: screenshots will be generated only if E2E test failed
-    - uses: actions/upload-artifact@v2
-      if: failure() || true
-      with:
-        name: cypress-screenshots
-        path: ./Tests/integration-tests/cypress/screenshots
-        if-no-files-found: ignore
-        
+        # after the test run completes
+        # store screenshots
+        # NOTE: screenshots will be generated only if E2E test failed
+      - uses: actions/upload-artifact@v2
+        if: failure() || true
+        with:
+          name: cypress-screenshots
+          path: ./Tests/integration-tests/cypress/screenshots
+          if-no-files-found: ignore
